# Title: Composer API YAML file
# Date: NOvember 10, 2022
# Author: Jamal Eddine Damir
# Description: YAML file describing the operations of the Composer API
# Sources:
# Source code from class GitHub Repository
# Instructor provided assignment specific instructions

openapi: "3.0.0"
info:
  title: Composer API
  version: 1.0.0
paths:
  /composers:
    get:
      tags:
        - Composers
      description: API for returning an list of composers from MongoDB Atlas.
      summary: returns a list of composer documents.
      responses:
        "200":
          description: Composer documents
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
    post:
      tags:
        - Composers
      description: API for adding new composer objects.
      summary: Creates a new composer object.
      requestBody:
        description: Composer information.
        content:
          application/json:
            schema:
              required:
                - firstName
                - lastName
              properties:
                firstName:
                  type: string
                lastname:
                  type: string
      responses:
        "200":
          description: Composer added
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
  /composers/{id}:
    get:
      tags:
        - Composers
      description: API for returning a single composer object from MongoDB.
      summary: returns a composer documents.
      parameters:
        - name: id
          in: path
          required: true
          description: The composerId requested by the user.
          schema:
            type: string
      responses:
        "200":
          description: Composer document is JSON format
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
